---
- name: Palo Alto Create Firewall Policies
  hosts: localhost
  connection: local
  gather_facts: false
 
  tasks:
  - name: Add Rules at Specific Location in the Rule Base
    include_role:
      name: create_security_policies
      vars_from: "password.yml"
