---
- name: Palo Alto Create Firewall Policies
  hosts: localhost
  connection: local
  gather_facts: false
  environment:
    PYTHONHTTPSVERIFY: 0
  vars:
    provider: '{"ip_address": "{{ 10.180.0.145 }}"}'

  tasks:
  - name: Add Rules at Specific Location in the Rule Base
    include_role:
      name: create_security_policies
      vars_from: "password.yml"
