---
- name: Palo Alto Create Firewall Policies
  hosts: localhost
  connection: local
  gather_facts: false
  environment:
    PYTHONHTTPSVERIFY: 0
  vars:
    provider: '{"api_key": "LUFRPT12em9rcFNUSktTSHJEVHBXUTFIL2QwY1ZCa3c9NEFNNXpmUHk0dnh1TjNicndnMzVKUT09", "ip_address": "10.180.0.145"}'

  tasks:
  - name: Add Rules at Specific Location in the Rule Base
