--- 
- 
  name: "Read CSV File"
  read_csv: 
    path: roles/create_security_policies/files/firewall_policy_requirements.csv
  register: firewall_policies
- 
  name: "Add rules at specific location in the rulebase"
  panos_security_rule: 
    action: "{{ firewall_policies.list[item]['Action'] }}"
    application: 
      - "{{ firewall_policies.list[item]['Application'] }}"
    category: 
      - "{{ firewall_policies.list[item]['Category'] }}"
    description: "{{ firewall_policies.list[item]['Rule Description'] }}"
    destination_ip: 
      - "{{ firewall_policies.list[item]['Destination IP'] }}"
    destination_zone: 
      - "{{ firewall_policies.list[item]['Destination Zone'] }}"
    existing_rule: "{{ firewall_policies.list[item]['Existing Rule'] }}"
    location: "{{ firewall_policies.list[item]['Location'] }}"
    provider: "{{ provider }}"
    rule_name: "{{ firewall_policies.list[item]['Rule Name'] }}"
    service: 
      - "{{ firewall_policies.list[item]['Service'] }}"
    source_ip: 
      - "{{ firewall_policies.list[item]['Source IP'] }}"
    source_user: 
      - "{{ firewall_policies.list[item]['Source User'] }}"
    source_zone: 
      - "{{ firewall_policies.list[item]['Source Zone'] }}"
